### ISSUE TITLE
Compile error after update to 2.41.0

### ISSUE THREAD

**Issue by Terbium-135** [elixir-cldr/cldr#254]
After upgrade:

```
Upgraded:
  ex_cldr 2.40.3 => 2.41.0
  ex_cldr_calendars 2.0.0 => 2.1.0
  ex_cldr_dates_times 2.21.0 => 2.22.0
  ex_cldr_locale_display 1.5.0 => 1.6.0
  ex_cldr_units 3.17.2 => 3.18.0
  unicode_string 1.5.0 => 1.6.0
* Updating ex_cldr_units (Hex package)
* Updating ex_cldr_dates_times (Hex package)
* Updating ex_cldr_locale_display (Hex package)
* Updating ex_cldr (Hex package)
* Updating unicode_string (Hex package)
* Updating ex_cldr_calendars (Hex package)
```

I get the following error:

```
== Compilation error in file lib/backend/prices.ex ==
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a valid pattern

    (stdlib 6.2) :binary.matches("4.00", %{standard: ","})
    (elixir 1.18.3) lib/string.ex:1619: String.replace_guarded/4
    (ex_money 5.19.2) lib/money.ex:2943: Money.parse_decimal/3
    (ex_money 5.19.2) lib/money.ex:2957: Money.maybe_decimal/2
    (ex_money 5.19.2) lib/money.ex:272: Money.new/3
    lib/backend/prices.ex:33: (module)
```

Source code:

![Image](https://github.com/user-attachments/assets/b3a067ce-14c1-4b1b-9f1e-816f9b129d30)

Did I miss something obvious?

**Comment by kipcole9** [comment]
Yes, `ex_money` version 5.20.0 isn't yet on hex - I was hoping you could try it from GitHub. But I think its solid enough to release now so I'll do that.

**Comment by Terbium-135** [comment]
Compiling nicely with the github version of ex_money.

Thanks once again for being a fast responder Kip
