### ISSUE TITLE
Compilation error for `da` locale v2.43.0

### ISSUE THREAD

**Issue by benregn** [elixir-cldr/cldr#261]
Hey Kip,

I'm getting a compilation error after bumping ex_cldr from v2.42.0 to v2.43.0.

Error:

```
11:47:27.258 [info] Downloaded locale :da version v2.43.0
Generating MyApp.Cldr for 3 locales named [:da, :en, :und] with a default locale named :da
Compiling lib/my_app/cldr.ex (it's taking more than 10s)

== Compilation error in file lib/my_app/cldr.ex ==
** (KeyError) key :daylight_savings not found in: %{
  generic: [0, "-tid"],
  standard: [0, "-normaltid"],
  daylight: [0, "-sommertid"]
}. Did you mean:

      * :daylight

    lib/my_app/cldr.ex:1: anonymous fn/3 in :elixir_compiler_2771.__MODULE__/1
    (elixir 1.18.3) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/my_app/cldr.ex:1: (module)
    (ex_cldr 2.43.0) /Users/tomas/projects/my_app/my_app/lib/my_app/cldr.ex:1: Cldr.Backend.Compiler.__before_compile__/1
```

Elixir version:

```
elixir --version                                                                                
Erlang/OTP 27 [erts-15.2.3] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.18.3 (compiled with Erlang/OTP 27)
```

I did nuke the `_build` and `deps` dir and deleted the locale file `rm priv/cldr/locales/da.json`.

**Comment by kipcole9** [comment]
I think this means you also need to update `ex_cldr_dates_times`.  Unfortunately there's no way for me to signal (in code) that a dependency also needs to be updated. But I certainly should have put that in the changelog.

Does that sounds like it might make sense?
