### ISSUE TITLE
Compilation error after upgrading from 2.37.5 to 2.38.0

### ISSUE THREAD

**Issue by Terbium-135** [elixir-cldr/cldr#229]
Getting this after upgrade:
```
== Compilation error in file lib/cldr/territory.ex ==
** (Protocol.UndefinedError) protocol Enumerable not implemented for :AW of type Atom
    (elixir 1.16.2) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.16.2) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.16.2) lib/enum.ex:4396: Enum.map/2
    lib/cldr/territory.ex:16: anonymous fn/1 in :elixir_compiler_8.__MODULE__/1
    (elixir 1.16.2) lib/map.ex:257: Map.do_map/2
    (elixir 1.16.2) lib/map.ex:257: Map.do_map/2
    (elixir 1.16.2) lib/map.ex:251: Map.new_from_map/2
    lib/cldr/territory.ex:14: (module)

```

Looks similar to issue https://github.com/elixir-cldr/cldr/issues/216

**Comment by kipcole9** [comment]
This is a duplicate of https://github.com/elixir-cldr/cldr_territories/issues/42 so closing here in favour of that issue.  Thanks for the report and sorry for the inconvenience.
