### ISSUE TITLE
Compilation error in lib/cldr/config/rbnf_config.ex

### ISSUE THREAD

**Issue by dkln** [elixir-cldr/cldr#170]
First of all: thanks for this awesome hex package 💪 

When I upgrade to 2.27.0 I get the following compilation error:

```
== Compilation error in file lib/cldr/config/rbnf_config.ex ==
** (ArgumentError) The environment variable $CLDR_PRODUCTION must be set to the
directory where the CLDR json data is stored.

See DEVELOPMENT.md for more information about CLDR data
and generating the json files.

    lib/cldr/config/config.ex:202: Cldr.Config.download_data_dir/0
    lib/cldr/config/rbnf_config.ex:9: (module)
```

I am using Elixir 1.13.0 and OTP 24. Occurs on both OSX (12.2.1) and Debian (11.x)
Is this is a bug or am I missing some configuration?

**Comment by kipcole9** [comment]
Thanks for the report and many apologies for the inconvenience. A really terrible error that resulted from leaking context from a development environment into the hex package.  I have retired `2.27.0` and published [ex_cldr version 2.27.1](https://hex.pm/packages/ex_cldr/2.27.1).  The changelog entry is:

### Bug Fixes

* Don't depend on CLDR product data being available at compile time. Eggregious error inserted in release 2.27.0. Thanks to @dkln for the report. Closes #170.

I believe you should no longer have this error but of course please reopen if you see an issue.

**Comment by dkln** [comment]
Not a problem! Thanks for the fix and all the hard work on this hex package 👍
