### ISSUE TITLE
Compilation error with OTP-28

### ISSUE THREAD

**Issue by GRoguelon** [elixir-cldr/cldr#259]
Hi, 

I have tried to upgrade my project to OTP 28.0.1 and Elixir 1.18.4-otp-28.

I got this error which prevents me to complete compilation:

```
Generating MyProject.Cldr for 2 locales named [:en, :und] with a default locale named :en

== Compilation error in file lib/my_project/cldr.ex ==
** (ArgumentError) cannot escape #Reference<0.1510396911.1037172739.95748>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
    (elixir 1.18.4) src/elixir_quote.erl:554: :elixir_quote.argument_error/1
    (elixir 1.18.4) src/elixir_quote.erl:462: :elixir_quote.do_quote_simple_list/3
    (elixir 1.18.4) src/elixir_quote.erl:462: :elixir_quote.do_quote_simple_list/3
    (elixir 1.18.4) src/elixir_quote.erl:150: :elixir_quote.do_escape/2
    (elixir 1.18.4) src/elixir_quote.erl:170: :elixir_quote."-do_escape/2-lc$^1/1-0-"/3
    (elixir 1.18.4) src/elixir_quote.erl:171: :elixir_quote."-do_escape/2-lc$^1/1-0-"/3
    (elixir 1.18.4) src/elixir_quote.erl:171: :elixir_quote.do_escape/2
    my_project/lib/my_project/cldr.ex:1: (file)
```

I have this module:

```elixir
defmodule MyProject.Cldr do
  use Cldr, locales: [:en], default_locale: :en, providers: [Cldr.Number, Cldr.Calendar, Cldr.DateTime, Cldr.List]
end
```

I had a similar issue with my file `endpoint.ex` where I had a Regex in a module attribute, I tried to review the file `lib/cldr/cldr.ex` but I couldn't identify any of the deprecated changes of OTP-28.

**Comment by GRoguelon** [comment]
FYI, with Elixir `1.19.0-rc.0-otp-28`:
```
** (ArgumentError) ~r/[\:：﹕︓∶]/u contains a reference (#Reference<0.1558792702.3750625282.110130>) and therefore it cannot be escaped (it must be defined within a function instead). The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
    (elixir 1.19.0-rc.0) src/elixir_quote.erl:572: :elixir_quote.argument_error/1
    (elixir 1.19.0-rc.0) src/elixir_quote.erl:167: :elixir_quote."-do_escape/2-lc$^1/1-0-"/3
    (elixir 1.19.0-rc.0) src/elixir_quote.erl:167: :elixir_quote."-do_escape/2-lc$^1/1-0-"/3
    (elixir 1.19.0-rc.0) src/elixir_quote.erl:167: :elixir_quote.do_escape/2
    (elixir 1.19.0-rc.0) src/elixir_quote.erl:213: :elixir_quote.escape_map_key_value/4
    (elixir 1.19.0-rc.0) src/elixir_quote.erl:167: :elixir_quote."-do_escape/2-lc$^1/1-0-"/3
    (elixir 1.19.0-rc.0) src/elixir_quote.erl:167: :elixir_quote.do_escape/2
    my_project/lib/my_project/cldr.ex:1: (file)
```

**Comment by GRoguelon** [comment]
> That's still using OTP 28.0 though. The fixes will likely be in OTP 28.1: [erlang/otp#9976](https://github.com/erlang/otp/pull/9976)

Thank you for sharing the OTP issue. I will wait for 28.1

**Comment by kipcole9** [comment]
All the `ex_cldr` libraries are expected to work on Erlang 28.0 and Elixir 1.18.4. So. your compilation error means I've missed something. I'm working on that now.

**Comment by kipcole9** [comment]
Can you share the library versions you are using? I've run a number of tests now on OTP 28.0.1 and Elixit 1.18.4-otp-27 without compilation error. Hence why I suspect you may not have updated your dependencies.

**Comment by GRoguelon** [comment]
> You'll need to relax your dependency configuration for `ex_cldr`. Typically you would have `{:ex_cldr, "~> 2.42"}` in order to support OTP 28 and the upcoming Elixir 1.19.
> 
> Basically, you need to be on the latest release of the _all_ the `ex_cldr` libs to have OTP 28 support.

Just did it and ran our CI and everything looks good with Cldr 💪 

Sorry for the false alert, thank you for the assistance.

Can I close this issue?

**Comment by kipcole9** [comment]
Glad you're back on track!
